# Generated by Django 4.0.5 on 2022-06-08 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 10, 50, 42, 742075)),
        ),
    ]
